arduino/ArduinoCore-renesas

.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml
.github/workflows/sync-labels.yml

[`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) is an access token provided automatically by GitHub Actions. The default permissions of this token for workflow runs in a trusted context (i.e., not triggered by a PR from a fork) are set in the [enterprise](https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#enforcing-a-policy-for-workflow-permissions-in-your-enterprise)/[organization](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#setting-the-permissions-of-the-github_token-for-your-organization)/[repository](https://docs.github.com/en/repositories/ …

Configure permissions of `GITHUB_TOKEN` in workflows

---

.github/workflows/compile-examples.yml
.github/workflows/sync-labels.yml

The repository's GitHub Actions workflows use several GitHub Actions actions. The steps that use the actions [pin the dependency to a major version series](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions). This means the specific dependency version is unmanaged within that major version series, but the reference must be updated after there is a new major version release of the dependency.
Several of the dependencies were pinned to outdated major version refs, causing the workflows to miss the benefits of recent development work on those dependencies. They are hereby updated to the latest major version refs. The breaking changes that caused the major version bumps in the dependencies are not relevant to our usage of them so no …

Update action dependencies of GitHub Actions workflows

---

.github/workflows/sync-labels.yml

GitHub Actions provides the capability for workflow authors to use the capabilities of the GitHub Actions ToolKit package directly in the `run` keys of workflows via "[workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions)". One such command is `set-output`, which allows data to be passed out of a workflow step as an output.
It has been determined that this command has potential to be a security risk in some applications. For this reason, GitHub has deprecated the command and a warning of this is shown in the workflow run summary page of any workflow using it:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …

Migrate "Sync Labels" workflow from deprecated `set-output` commands

---

.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml

Previously, the development versions of Arduino's sketch compilation actions were used in the project's GitHub Actions workflows. Using release versions of the actions instead provides a more stable CI system.
Use of the major version ref will cause the workflow to benefit from ongoing development to the action up until such time as a new major release is made, at which time we would need to evaluate whether any changes to the workflow are required by the breaking change that triggered the major release before updating the major ref (e.g., `uses: arduino/compile-sketches@v1` -> `uses: arduino/compile-sketches@v2`).

Pin sketch compilation actions to major version refs

---

libraries/BlockDevices/BlockDevice.h
libraries/BlockDevices/CodeFlashBlockDevice.h
libraries/BlockDevices/DataFlashBlockDevice.h
libraries/BlockDevices/SDCardBlockDevice.cpp

Fixes undefined behavior where SDCardBlockDevice::wait_for_completition() runs off the end without returning a value.

Fix undefined behavior

---

libraries/SPI/SPI.cpp

#12 
The logical not in [this line](https://github.com/arduino/ArduinoCore-renesas/blob/149f78b6490ccbafeb420f68919c381a5bdb6e21/libraries/SPI/SPI.cpp#L386C38-L386C38) makes the mask 0 and wipes out the earlier settings. This should be a bitwise not, but even so the `0xFF` would also mask off the SSLA bits b6-b4 and half of the SPB bits b9-b8. Changing `0xFF` to `3` will clear just the BRDV bits b3-b2.

Fix SPI mode and bit order settings

---

libraries/WiFiS3/src/Modem.cpp
libraries/WiFiS3/src/WiFiClient.cpp
libraries/WiFiS3/src/WiFiClient.h
libraries/WiFiS3/src/WiFiSSLClient.cpp
libraries/WiFiS3/src/WiFiSSLClient.h
libraries/WiFiS3/src/WiFiUdp.cpp
libraries/WiFiS3/src/WiFiUdp.h

fixing the problem of readString not working on UDP string R4 example
@tigoe

Read string not working fix

---

libraries/WiFiS3/src/Modem.cpp
libraries/WiFiS3/src/Modem.h

refactoring debug functions for Uno R4 Wifi

refactoring debug for uno R4 wifi

---

libraries/WiFi/extra/combine.py

Add combine script to make a monolithic binary that can be flashed at 0x0.
This produces `ESP32-C3.bin` file (a different name can be specified as parameter).
The script has all the offset from [here](https://github.com/bcmi-labs/ArduinoCore-renesas/blob/main/libraries/WiFi/extra/flasher.sh) and seems to work fine when flashed on a C33 with `$ espflash write-bin -p /dev/ttyACM1 -b 230400 0x0 ESP32-C3.bin` (version of espflash 2.0.0). 
It's based on https://github.com/arduino/nina-fw/blob/master/combine.py

Add script to generate monolithic fw binary

---

libraries/AnalogWave/examples/DACEqualTemperedScale/DACEqualTemperedScale.ino
libraries/AnalogWave/examples/DACJacques/DACJacques.ino

This Pull Request adds 2 DAC Examples provided by Tom Igoe to the Core of the UNO R4

Adds Toms UNO R4 DAC examples to the AnalogWave core library

---

libraries/RTC/examples/RTC_NTPSync/RTC_NTPSync.ino

This PR makes the RTC NPT Sync example sketch compatible with the UNO R4 WiFi.

Make RTC sketch compatible with UNO R4 WiFi

---

libraries/Arduino_LED_Matrix/examples/LivePreview/LivePreview.ino

The removed comment line references an interface element that doesn't exist in the LED Matrix editor anymore.

Remove LED Matrix Live preview sketch comment

---

libraries/AnalogWave/examples/SineWave/SineWave.ino

SineWave example of the AnalogWave library was using A0 as an input pin, but the A0 pin is the DAC output pin.
https://forum.arduino.cc/t/invalid-r4-sinewave-ino-example/1149139
This PR changes the potentiometer input pin to A5, to match the other DAC examples in the library.

Update sineWave example of AnalogWave core library

---

libraries/RTC/examples/RTC_NTPSync/RTC_NTPSync.ino

This is a simplified version of the RTC NTP sync example that uses an existing library to handle everything NTP instead of reinventing the wheel. I'm not sure if we want to avoid having such dependencies. Any feedback on this @facchinm ?

Use library for NTP data handling

---

variants/MINIMA/pins_arduino.h
variants/PORTENTA_C33/pins_arduino.h
variants/UNOWIFIR4/pins_arduino.h

@aentinger 
Sorry for the delay in getting this to you.  Got side tracked with a weird issue as I was trying to get the Encoder library updated so people can use with the R4 boards.  But in accordance with your request for me to submit a PR for [ArduinoEigen] Pin Definitions Conflict with Sketch/Library Variables when used with ArduinoCore-renesas Issue https://github.com/arduino/ArduinoCore-renesas/issues/50 this is the update.   As I mentioned "constexpr" throws a error so I left it as const like the analog pins.  Out of curiosity what version of c++ are the R4 using? 
regards
Mike

Define digital pins via `static const` instead of `#define`

---

libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

Currently if you write a sketch that relies on knowing when a sequence completes, by having your code call sequenceDone(), this will only work if your sketch sets a non-null callback function, as the code that sets the condition is currently in the if block:
```
if(_callBack != nullptr){
```
Simply moved the line to after the if block

LED_matrix: move _sequenceDone = true out of if block

---

libraries/WiFiS3/src/WiFiS3.h

ciao @tigoe can you use this pull request to check the compatibility with the wifiNINA:SSLclient examples?
Basically just including this and testing the usage of WiFISSLclient i notice that when and end point is public them works

fix for compatibility SSL

---

libraries/RTC/src/RTC.cpp

Resolves compilers generating the wrong assembly per https://github.com/arduino/ArduinoCore-renesas/issues/88

Fix undefined behavior in RTC.begin()

---

cores/arduino/analog.cpp

on startup, `analogReference()` is being called to read the real value of 5V voltage so there's a way to retrieve the real voltage via `analogRead()`.
However, calling `R_ADC_Close` when the ADC is not yet open triggers a chain of events that ends up at
```
__STATIC_INLINE void R_FSP_IsrContextSet (IRQn_Type const irq, void * p_context) {
gp_renesas_isr_context[irq] = p_context;
}
```
If the irq is not initialized, setting `gp_renesas_isr_context[somethig]` will overwrite random memory.
Fixes https://github.com/arduino/ArduinoCore-renesas/issues/76

analogReference: fix heap corruption

---

.gitignore
cores/arduino/time.cpp

See [issue 49](https://github.com/arduino/ArduinoCore-renesas/issues/49)
1. Fix for anomaly in micros() when the counter wrapped just before it was read (same solution as in R3 code)
2. Specify timer configuration as constants to make micros() considerably faster

Bugfix: `micros()` returns smaller number when timer wraps

---

platform.txt

The definition is needed by time.h (see https://github.com/arduino-libraries/MKRGSM/commit/019b0e1195127bd2be48039a4e17b51f285931d8) but we missed to give it a proper value :|
Defining to 700 is ok for POSIX 2017, so strnlen prototype gets picked up
Fixes https://github.com/arduino/ArduinoCore-renesas/issues/18

platform: properly define _XOPEN_SOURCE

---

libraries/Wire/Wire.cpp
libraries/Wire/Wire.h

clock source is fixed for RA4M1, so the rates will be wrong for C33.
This will be fixed in the next commit

Wire: fix setClock

---

libraries/BlockDevices/SDCardBlockDevice.cpp

LittleFileSystem::reformat() on the SD Card block device internally runs LittleFileSystem::format() and then LittleFileSystem::mount() in a sequence. After LittleFileSystem::format()'s main job is performed using the LittleFS file system driver one level below it, it runs deinit() on the block device. That leads, after a series of calls, to a call to the Renesas FSP function R_SDHI_Close(), which sets the initialized field of the ctrl structure to false. LittleFileSystem::mount() runs next, and begins by running init() on the block device, but because it's still in a state where card_inserted and initialized are true, full initialization doesn't occur - only parts of it. This leaves the initialized field of the ctrl structure being false, which leads to the FSP-internal function …

Fix LittleFS formatting freeze bug

---

cores/arduino/usb/USB.cpp
libraries/UsbHostMsd/UsbHostMsd.cpp
libraries/UsbHostMsd/tu_msc.c
variants/MINIMA/pins_arduino.h
variants/PORTENTA_C33/tusb_config.h
variants/UNOWIFIR4/pins_arduino.h

Since the patches for USB HS (Portenta C33) have been merged in mainline, we can safely abandon our fork.
Some modifications are required for changed APIs, plus HUB host support has been added for C33

Update tinyusb submodule to track mainline

---

cores/arduino/usb/SerialUSB.cpp
variants/PORTENTA_C33/tusb_config.h

Should fix https://github.com/arduino/ArduinoCore-renesas/issues/104
@pennam @Kees-van-der-Oord

usb: c33: fix serial errors

---

cores/arduino/Arduino.h
cores/arduino/Interrupts.cpp
cores/arduino/Serial.cpp
cores/arduino/pwm.cpp
cores/arduino/variant_helper.cpp
libraries/Arduino_CAN/src/R7FA4M1_CAN.cpp
libraries/Arduino_CAN/src/R7FA6M5_CAN.cpp
libraries/SPI/SPI.cpp
libraries/Wire/Wire.cpp
variants/MINIMA/pins_arduino.h
variants/MINIMA/variant.cpp
variants/MUXTO/pins_arduino.h
variants/MUXTO/variant.cpp
variants/PORTENTA_C33/pins_arduino.h
variants/PORTENTA_C33/variant.cpp
variants/UNOWIFIR4/pins_arduino.h
variants/UNOWIFIR4/variant.cpp

Fixes https://github.com/arduino/ArduinoCore-renesas/issues/102
@WestfW this should fix the PINCOUNT macro being partially missing, while refactoring the code to use it.

Restore and use PINCOUNT_fn() wrapper

---

variants/MINIMA/pins_arduino.h
variants/MINIMA/variant.cpp
variants/UNOWIFIR4/pins_arduino.h

Fix pin numbers macros on UNO R4

---

extras/e2studioProjects/portenta_h33_lib/configuration.xml
libraries/Arduino_CAN/examples/CAN1Write/CAN1Write.ino
libraries/Arduino_CAN/examples/CANWrite/CANWrite.ino
libraries/Arduino_CAN/keywords.txt
libraries/Arduino_CAN/src/R7FA4M1_CAN.cpp
libraries/Arduino_CAN/src/R7FA6M5_CAN.cpp
libraries/Arduino_CAN/src/R7FA6M5_CAN_AFL.c
variants/PORTENTA_C33/includes/ra_cfg/fsp_cfg/r_canfd_cfg.h

This fixes #36.
Requires https://github.com/arduino/ArduinoCore-API/pull/194 .

[Arduino_CAN] support both 11-Bit (standard) and 29-Bit (extended) IDs.

---

cores/arduino/main.cpp
platform.txt

The _sbrk() function wasn't implemented. It's used by malloc() to request more heap memory. This function must be defined and correctly implemented if we want malloc() to return a null pointer if more space is requested than is available. It already works that way for the Mbed Core (although with a different implementation), but doesn't for the Renesas Core before this addition.

Fix that malloc() doesn't return a null pointer for too large allocations

---

cores/arduino/FspTimer.cpp
cores/arduino/FspTimer.h

If the begin method:
```
/* -------------------------------------------------------------------------- */
bool FspTimer::begin(timer_mode_t mode, uint8_t tp, uint8_t channel, float freq_hz, float duty_perc, GPTimerCbk_f cbk /*= nullptr*/ , void *ctx /*= nullptr*/  ) {
/* -------------------------------------------------------------------------- */
```
Is called with the tp=1 (AGT)
It will fail as this method uses the member variable type to decide if it is working with GPT or AGT.  Problem is that this member is not set until after the code has decided that the parameters are correct and it then calls the begin with the period counts.
So needed to use the passed in parameter tp instead.  Also  this begin method called set_period_counts to convert the data into the counts.  This method …

FspTimer does not initialize properly if AGT timer is selected.

---

libraries/SSLClient/src/ssl_fs_io.cpp

Testing other things i noticed that certificate loading from filesystem is failing with some sketches. By default certificates are stored in the first partition of the QSPI flash so passing the raw block device is wrong.

C33 SSLClient: fix certificate loading from filesystem

---

cores/arduino/FspTimer.cpp
cores/arduino/FspTimer.h

During code review of changes I made to the Servo library: https://github.com/arduino-libraries/Servo/pull/116
@iabdalkader requested that I move all of the platform specific timer changes into the core instead of being in the hardware specific sub-directory of the Servo library.
This change adds a method to tell the GPT timer, that when I make a change to the pseriod (set_period(p) ) that I want the change to happen now and not be buffered.
And updated the set_period method to check for this and directly set the not buffered register with the new period.

Add method to allow the GPT Timer period not to be buffered.

---

platform.txt

I think the `tinyusb path` should use core platform path `{build.core.path}`, not board platform path `{runtime.platform.path}`.
the board platform can still override it in its platform.txt

platform.txt - core platform path for tinyusb

---

libraries/WiFiS3/examples/AP_SimpleWebServer/AP_SimpleWebServer.ino
libraries/WiFiS3/examples/ConnectWithWPA/ConnectWithWPA.ino
libraries/WiFiS3/examples/ScanNetworks/ScanNetworks.ino
libraries/WiFiS3/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
libraries/WiFiS3/examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino
libraries/WiFiS3/examples/WiFiChatServer/WiFiChatServer.ino
libraries/WiFiS3/examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino
libraries/WiFiS3/examples/WiFiUdpSendReceiveString/WiFiUdpSendReceiveString.ino
libraries/WiFiS3/examples/WiFiWebClient/WiFiWebClient.ino
libraries/WiFiS3/examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino
libraries/WiFiS3/examples/WiFiWebClientSSL/WiFiWebClientSSL.ino
libraries/WiFiS3/examples/WiFiWebServer/WiFiWebServer.ino

Hi, when I was browsing https://docs.arduino.cc/tutorials/uno-r4-wifi/wifi-examples, I noticed that the descriptions in the comments of the code were incorrect. All examples related to networking were written as RTC. So, I tried to [edit the document](https://github.com/arduino/docs-content/blob/main/content/hardware/02.hero/boards/uno-r4-wifi/tutorials/wifi-examples/wifi-examples.md?plain=1). Later on, I found that the code in the document is based on the corresponding example code from this repository, so I made this modification here. Hope these modifications can be helpful.

Fix the incorrect comments in the examples of the WIFI S3 library.

---

libraries/RTC/src/RTC.cpp

This fixes issue on RTC: the set Alarm only worked for 1 field (seconds or minutes or hours and so on...).
https://github.com/arduino/ArduinoCore-renesas/issues/154

Fix for RTC not allowing matching more than one field on Alarm

---

libraries/UsbMsd/examples/MSD_QSPI/MSD_QSPI.ino

By default Portenta C33 QSPI flash is partitioned with this scheme https://github.com/arduino/ArduinoCore-renesas/blob/b82e6428078fb988618dfb252c4e32fc2fdad011/libraries/Storage/examples/QSPIFormat/QSPIFormat.ino#L55-L56
With this changes both partitions are mounted as mass storage. If user partition is formatted as LittleFS it will be skipped.

Portenta C33: Msd QSPI examples, mount both partition

---

libraries/UsbHostMsd/UsbHostMsd.cpp
libraries/UsbHostMsd/UsbHostMsd.h
libraries/UsbHostMsd/tu_msc.c

Adds a USB mass storage disconnected callback in a similar style as the connected callback.

Add a USB mass storage disconnected callback

---

libraries/SSLClient/src/SSLClient.cpp
libraries/SSLClient/src/SSLClient.h
libraries/lwIpWrapper/src/lwipClient.h

Avoid shadowing Stream.setTimeout

---

libraries/SFU/examples/OTAUpdate/OTAUpdate.ino
libraries/SFU/examples/OTAUpdate/arduino_secrets.h
libraries/SFU/src/SFU.cpp
libraries/SFU/src/SFU.h

SFU add download function and OTA example

---

variants/PORTENTA_C33/tusb_config.h

A problem occurs when get_new_address() returns address 5, and that number ends up at this line as dev_addr:
_hcd.ep[dev_addr - 1][dir_in][epn - 1] = num;
in hcd_edpt_open() in hcd_rusb2.c(). It becomes 4 and is then used to index the ep array. There's an assert that checks that the address is below 6, so it passes the assert:
TU_ASSERT(dev_addr < 6);
Then the 4 is used as the first index of the ep array, which is defined like so:
uint8_t ep[4][2][15];
This index may only be 0 to 3, so the array is now indexed outside its bounds. And then num is written to that location, which corrupts memory at random locations.
It can be worked around by lowering the value of CFG_TUH_DEVICE_MAX in the configuration file by one. I've also created an issue for TinyUSB.

Fix memory corruption bug

---

libraries/Arduino_CAN/examples/CANReadFilter/CANReadFilter.ino
libraries/Arduino_CAN/keywords.txt
libraries/Arduino_CAN/src/R7FA4M1_CAN.cpp
libraries/Arduino_CAN/src/R7FA4M1_CAN.h

CAN Filter and Mask

---

libraries/WiFi/src/WiFi.cpp
libraries/WiFi/src/WiFiC3.h

DHCP was overwriting static IP configuration. This PR solves it. It is done same way as in esp32 and esp8266 WiFi library, which too use LwIP .  
It allows to return to DHCP with `config(0)`

WiFiC3 - don't start DHCP in begin, if static IP is configured

---

libraries/WiFiS3/src/WiFi.cpp

Fixes a bug which I guess was introduced while adopting `void CWifi::config(IPAddress local_ip)` from a copy of
```
void CWifi::config(IPAddress local_ip, IPAddress dns_server) {
/* -------------------------------------------------------------------------- */
IPAddress _gw(local_ip[0],local_ip[1], local_ip[2], 1);
IPAddress _sm(255,255,255,0);
IPAddress dns(0,0,0,0);
return _config(local_ip, _gw, _sm,dns_server,dns);
}
```

WiFiS3 - static IP config, fix automatic DNS IP

---

libraries/RTC/examples/RTC_AutomaticExample/RTC_AutomaticExample.ino
libraries/RTC/examples/Test_RTC/Test_RTC.ino

Currently some of the RTC examples include Serial.print() calls in callback functions that are triggered by an ISR. This is bad practice because:
- Serial.print() can depend on interrupts, which are disabled while another ISR function is running. 
- ISR functions should be as short and quick as possible.
This PR removes Serial.print() calls from callback functions in the RTC example sketches.
They are replaced by flags and conditional statements in the loops, keeping the callback functions as short as possible.

RTC - Replace Serial.print()s from ISR functions in example Sketches

---

variants/MINIMA/variant.cpp
variants/UNOWIFIR4/variant.cpp

Fixes https://github.com/arduino/ArduinoCore-renesas/issues/160
Special thanks to @simooon442 for spotting the issue

unor4: fix incorrect BSP_CLOCK_CFG_SUBCLOCK_POPULATED defines

---

libraries/Arduino_CAN/extras/test/CMakeLists.txt

Running the Arduino_CAN unit tests fails otherwise.

Fix: provide include path to where the API folder is stored.

---

.gitignore
cores/arduino/IRQManager.cpp
cores/arduino/IRQManager.h
libraries/Wire/Wire.cpp
libraries/Wire/Wire.h

This PR solve https://github.com/arduino/ArduinoCore-renesas/issues/180 and supersedes https://github.com/arduino/ArduinoCore-renesas/pull/182.
Basically allow I2C to switch from master to slave and vice versa in a cleaner way (with less changes).

Allow Wire to switch from master to slave and vice versa

---

libraries/Wire/Wire.cpp

Fix TwoWire::read_from and TwoWire::write_to to use proper millis code that can handle rollover.  
Fixes issue https://github.com/arduino/ArduinoCore-renesas/issues/195

fixing millis rollover bug x2

---

libraries/WiFi/src/WiFi.cpp
libraries/WiFi/src/WiFiC3.h

WiFiS3 has it, ESP32 has it, it originates in ESP8266WiFi. in WiFiNINA it is approved for merge (merged in fw)
overview of WiFi/Ethernet getters and setters:
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#network-interface-getters-and-setters

WiFiC3 - dnsIP(n) getter added

---

cores/arduino/time.cpp

This fixes #194.
The following measurements were taken using the [Blink](https://github.com/arduino/arduino-examples/blob/main/examples/01.Basics/Blink/Blink.ino) example using a Arduino Uno R4 Minima.
**Before**:
**After**:

Fix: Increase accuracy of "delay()" routine.

---

cores/arduino/pwm.cpp
cores/arduino/pwm.h

This fixes #168 .
A short example sketch to test this could be:
```C++
#include "pwm.h"
PwmOut pwm_freq(3);
void setup()
{
Serial.begin(9600);
while (!Serial) { }
if (!pwm_freq.begin(10*1000*1000.0f, 50.0f))
Serial.println("Error");
}
void loop() {
}
```
1 MHz :heavy_check_mark: 
5 MHz :heavy_check_mark: 
10 MHz :heavy_check_mark: 
Although the generated frequency wanders ever more off the desired target. FYI @maidnl .

Provide frequency/duty_cycle API for PwmOut::begin(...).

---

libraries/WiFiS3/src/WiFiServer.cpp
libraries/WiFiS3/src/WiFiServer.h

Server implementation in the Ethernet library for W5x00 has operator bool.
WiFiServer in esp8266 and esp32 Arduino WiFi library has bool operator.

WiFiS3 WiFiServer operator bool

---

libraries/WiFiS3/examples/WiFiPagerServer/WiFiPagerServer.ino
libraries/WiFiS3/examples/WiFiPagerServer/arduino_secrets.h

to demonstrate how server.available and print-to-all-clients work
other libraries including the Ethernet library have this example I created because in other examples this is not so clear.
the example doesn't work right without the server.available fix in the S3 firmware https://github.com/arduino/uno-r4-wifi-usb-bridge/pull/20

WiFiS3 example WiFiPagerServer

---

libraries/lwIpWrapper/src/CNetIf.cpp

it returned own MAC. it should return BSSID of the AP it is joined to

WiFiC3 - STA BSSID getter fix

---

libraries/WiFi/examples/WiFiPagerServer/WiFiPagerServer.ino
libraries/WiFi/examples/WiFiPagerServer/arduino_secrets.h

to demonstrate how server.available and print-to-all-clients work
other libraries including the Ethernet library have this example I created because in the other examples this is not so clear.
btw: I play with the WiFiC3, lwIWrapper and ESPHost library on an Uno R4 with an ESP32 wired on SPI

WiFiC3 example WiFiPagerServer

---

libraries/WiFiS3/src/WiFiTypes.h
libraries/lwIpWrapper/src/CNetIf.h

previous WiFi libraries used the encryption type names ENC_TYPE_TKIP and ENC_TYPE_CCMP, which are based on the name of the encryption algorithm TKIP for WPA and CCMP for WPA2.
In WiFiS3 and WiFiC3 library constants with the well known marketing names WPA and WPA2 are used for encryption type constants.
this PR adds the legacy constants ENC_TYPE_TKIP and ENC_TYPE_CCMP  as aliases. 
EDIT: for WiFiC3 too

WiFiS3/C3 - add legacy wl_enc_type constants aliases

---

libraries/ESPhost/examples/ESP32_TEST/ESP32_TEST.ino

I guess the function was needed earlier in the development process but that no longer seems to be the case. Also doing some small other changes in order to get the sketch to compile.
Compilation/upload on Portenta C33 via
```bash
arduino-cli compile -b arduino-git:renesas:portenta_c33 -v examples/ESP32_TEST -u -p /dev/ttyACM0
```

Fix: compilation of "ESP32_Test.ino" fails due to non-existent function "begin".

---

libraries/WiFi/examples/ConnectWithWPA/ConnectWithWPA.ino
libraries/WiFi/examples/ScanNetworks/ScanNetworks.ino
libraries/WiFi/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
libraries/WiFi/src/WiFi.cpp

The firmware of the first WiFi library returned the MAC address in reversed ordering. It was fixed in examples and not in the `macAddress` method. Since then every WiFi library by Arduino reverses the MAC address in `macAddress` to reversed ordering and some reverse BSSID too. Then the examples print it reversed.
Why continue with this in new libraries? 
here BSSID was not reversed so examples printed it reversed.
overview of WiFi/Ethernet getters and setters:
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#network-interface-getters-and-setters

WiFiC3 - macAddress() return normal bytes ordering

---

libraries/WiFiS3/examples/ConnectWithWPA/ConnectWithWPA.ino
libraries/WiFiS3/examples/ScanNetworks/ScanNetworks.ino
libraries/WiFiS3/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
libraries/WiFiS3/src/WiFi.cpp
libraries/WiFiS3/src/WiFi.h

The firmware of the first WiFi library returned the MAC address in reversed ordering. It was fixed in examples and not in the `macAddress` method. Since then every WiFi library by Arduino reverses the MAC address in `macAddress` to reversed ordering and some reverse BSSID too. Then the examples print it reversed.
Why continue with this in new libraries? 
here BSSID was not reversed so examples printed it reversed.
overview of WiFi/Ethernet getters and setters:
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#network-interface-getters-and-setters

WiFiS3 - macAddress() return normal bytes ordering

---

libraries/lwIpWrapper/src/lwipClient.cpp

op bool should return false only for a 'null' client. a closed client may still have data to read. a Client returned from Server.available() should not fail on the usual bool test if it is closed but has data available.
in 'Arduino language' which doesn't use pointers or references, an empty Client with operator bool returning false is used instead of a NULL pointer. 
Implementations of Client operator bool in other libraries:
the WiFiNINA library
```
WiFiClient::operator bool() {
return _sock != 255;
}
```
the classic Ethernet library
```
virtual operator bool() { return _sockindex < MAX_SOCK_NUM; }
```
the MbedCore base class for WiFiClient and EthernetClient
```
operator bool() {
return sock != nullptr;
}
```

LwipClient - operator bool fix

---

libraries/Ethernet/src/Ethernet.cpp
libraries/Ethernet/src/EthernetC33.h

MACAddress getter as in other Ethernet library
[overview](https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#legacy-ethernet-getters-and-setters) of legacy Ethernet specific getters and setters in libraries

Ethernet - standard MACAddress getter with a parameter

---

libraries/ESPhost/examples/ESP32_TEST/ESP32_TEST.ino
libraries/ESPhost/src/CEspControl.h

ESPHost library - make the example work and remove unnecessary dependency to LwipWrapper library and its dependencies.
without the CNetIf.h include only the ESPHost library is used with the example.
with the unnecessary #include "CNetIf.h" it compiles the LwipWrapper library and all its dependencies
```
Using library ESPhost at version 1.0.0 in folder: /home/juraj/.arduino15/packages/arduino/hardware/renesas_portenta/1.0.5/libraries/ESPhost 
Using library lwIpWrapper at version 1.0.0 in folder: /home/juraj/.arduino15/packages/arduino/hardware/renesas_portenta/1.0.5/libraries/lwIpWrapper 
Using library Ethernet at version 1.0.0 in folder: /home/juraj/.arduino15/packages/arduino/hardware/renesas_portenta/1.0.5/libraries/Ethernet 
Using library SSLClient at version 1.1 in folder: …
```

ESPHost library - make the example work

---

libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphics/TextWithArduinoGraphics.ino
libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

Fix: prevent artefacts from appearing on the screen during a SCROLL_LEFT.

---

libraries/Ethernet/src/Ethernet.cpp
libraries/Ethernet/src/EthernetC33.h

Author of the STM32Ethernet library decided to change the ordering of the parameters for `begin` without `mac` address parameter. The EthernetC33 library is based on the STM32Ethernet library and the ordering of the parameters was not fixed.
The library is not yet used by many. It requires the Portenta C33 and a Portenta shield with Ethernet PHY module. So lets change the ordering of the parameters as soon as possible.

Ethernet.begin - fix parameters ordering

---

libraries/Ethernet/src/Ethernet.cpp
libraries/lwIpWrapper/src/CNetIf.cpp
libraries/lwIpWrapper/src/CNetIf.h

the missing `volatile` on `bool dhcp_acquired` in CNetIf.h caused problems for WiFi DHCP too. The waiting for DHCP ended only on timeout, but status() check then was OK because the IP address was set. So WiFi.begin just took long time.
I use Uno R4 to test Renesas Core LwIP networking. For WiFi I have an esp32 with the Hosted firmware on SPI and for Ethernet I replaced the EthernetDriver implementation with one over the W5500 driver (Ethernet 2 shied) from the esp8266 core. So I use `Ethernet.begin` methods with the MAC address parameter where some of this bugs appeared. The missing `restartAsyncRequest();` in `setMacAddress` stopped the periodic task so DHCP then timed out. After that I had in EthernetDriver a buffer smaller than the DHCP packet and the code just hang. It was the the …

EthernetC33 debugging

---

libraries/SSLClient/src/SSLClient.cpp

KeySlot was incorrectly encoded in a single byte.
As per https://github.com/NXPPlugNTrust/nano-package?tab=readme-ov-file#mbedtls-alt-files it should be stored over 4 bytes, in Big Endian order.

Fixed encoding of KeySlot ID.

---

platform.txt

This fixes #230 .
This change can be verified by examining the verbose compilation output (`-v`) when compiling a sketch **with** (`--optimize-for-debug`) and **without** optimization for debug turned on.
```bash
arduino-cli compile -b arduino-git:renesas:unor4wifi -v MySketch --optimize-for-debug
```
```bash
arduino-cli compile -b arduino-git:renesas:unor4wifi -v MySketch
```

Define the `compiler.optimization_flags` allows for specifying the desired optimization level during compilation.

---

libraries/SPI/SPI.cpp

See #244, when using buffer transfers with LSBFIRST the byte-order was wrong.

- fix for #244, byte-order wrong for LSBFIRST buffer transfers

---

bootloaders/UNO_R4/README.md

Starting from release 0.2.0 of uno-r4-wifi-usb-bridge firmware -dtr flag is needed in order to flash the bootloader

Docs: UNO R4 WiFi fix command to flash bootloader

---

.github/workflows/compile-examples.yml
libraries/Preferences/examples/Prefs2Struct/Prefs2Struct.ino
libraries/Preferences/examples/StartCounter/StartCounter.ino
libraries/Preferences/keywords.txt
libraries/Preferences/library.properties
libraries/Preferences/src/Preferences.cpp
libraries/Preferences/src/Preferences.h

Needs a new [uno-r4-wifi-usb-bridge](https://github.com/arduino/uno-r4-wifi-usb-bridge)  release

Add WiFi Preferences support

---

libraries/WiFiS3/examples/WiFiAdvancedChatServer/WiFiAdvancedChatServer.ino
libraries/WiFiS3/examples/WiFiAdvancedChatServer/arduino_secrets.h
libraries/WiFiS3/src/WiFiServer.cpp
libraries/WiFiS3/src/WiFiServer.h

corresponding PR for firmware is https://github.com/arduino/uno-r4-wifi-usb-bridge/pull/22
overview of Server implementations in libraries https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#server-class

WiFiS3 WiFiServer::accept()

---

libraries/WiFiS3/src/WiFiClient.cpp
libraries/WiFiS3/src/WiFiClient.h
libraries/WiFiS3/src/WiFiSSLClient.cpp

The corresponding PR in firmware is https://github.com/arduino/uno-r4-wifi-usb-bridge/pull/23
If connect timeout is not set on client, the library will use CONNECT commands which exist in older versions of the firmware. 
There is no need to use extra command to connect with IP address. The connect with hostname uses hostByName which first attempts to convert the string to IP address. So to avoid duplicate code, this PR redirects connect with IP to connect with hostname.
The Modem bug fix PR  https://github.com/arduino/ArduinoCore-renesas/pull/147 is need to see the effect of the timeout.
the checks will fail while the PR in firmware is not merged
overview of Client API in Arduino networking libraries:
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#client …

WiFiS3 client connect timeout

---

libraries/OTAUpdate/examples/OTA/OTA.ino
libraries/OTAUpdate/examples/WiFiFirmwareOTA/WiFiFirmwareOTA.ino
libraries/OTAUpdate/src/OTAUpdate.cpp
libraries/OTAUpdate/src/OTAUpdate.h

In this way if an error code changes in the wifi firmware there is no need to change this library

OTAUpdate: do not use Error enum to return error codes

---

libraries/SE05X/examples/SE05XAESEncryptandDecrypt/SE05XAESEncryptandDecrypt.ino
libraries/SE05X/examples/SE05XAESWriteKey/SE05XAESWriteKey.ino
libraries/SE05X/examples/SE05XHMAC/SE05XHMAC.ino
libraries/SE05X/src/SE05X.cpp
libraries/SE05X/src/SE05X.h
libraries/SE05X/src/lib/apdu/se05x_APDU_apis.h
libraries/SE05X/src/lib/apdu/se05x_APDU_impl.c
libraries/SE05X/src/lib/apdu/se05x_types.h

Add AES encrypt/decrypt and HMAC support for SE05X

---

libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

This fixes #259.
Instead the root cause for this issue was within ArduinoGraphics, for a detailed explanation see here: https://github.com/arduino-libraries/ArduinoGraphics/pull/36 .

Fix: do not randomly clear the first line of the LED matrix.

---

libraries/WiFiS3/src/WiFiSSLClient.cpp
libraries/WiFiS3/src/WiFiSSLClient.h

Apply after #253 
CI fails because new command definition is needed https://github.com/arduino/uno-r4-wifi-usb-bridge/pull/31

WiFiSSLClient: add setEccSlot method to configure client private key and certificate

---

libraries/ESPhost/src/CCtrlWrapper.h

SoftAP password length was checked for open network and was not checked for secured

ESPHost - fix softAP password check

---

cores/arduino/cm_backtrace/fault_handler/gcc/cmb_fault.S

On C33 and Minima an HardFault was redirected to a nonexistent serial port.

backtrace: remove spurious file from compiling

---

libraries/Wire/Wire.cpp

Fixes nasty bug when calling Wire.requestFrom(x, 3) and the first byte of the response was > 0x80

UNOR4: rebuild libfsp with I2C patch

---

libraries/Ethernet/src/Ethernet.cpp
libraries/WiFi/src/WiFi.cpp
libraries/lwIpWrapper/src/CNetIf.cpp
libraries/lwIpWrapper/src/CNetIf.h

It was not possible to reconnect to network with a different static IP. IP settings worked only for first invocation of `begin` (applied in CLwipIf::get). 
in CWifi::_config `netif_set_address` call was missing. 
in Ethernet::begin static IP was not applied if `ni` was already initialized.
Now new CNetIf.config does the static IP change for both.
discovered and tested with [WiFiTest](https://github.com/JAndrassy/NetApiHelpers/tree/master/examples/WiFiTest) and [LegacyEthernetTest](https://github.com/JAndrassy/NetApiHelpers/blob/master/examples/LegacyEthernetTest/LegacyEthernetTest.ino)

CNetIf - added config method to apply new static IP settings for WiFi and Ethernet

---

libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

While playing around with the LED matrix on my Arduino R4 WiFi I noticed that the function `ArduinoLEDMatrix::begin()` causes a compiler warning:
(This is what I observe after setting `Preferences -> Compiler Warnings` to `All`)
The reason appears to be very simple: `ArduinoLEDMatrix::begin()` is declared to return an `int`, but never returns anything. I think this is actually ok, since the function has nothing useful it could return. 
Thus I send you this PR to change it's return type from `int` to `void`.

Fix return type of ArduinoLEDMatrix::begin()

---

libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

This is a follow-up for #282 :
I missed in my previous PR that the return value from `FspTimer::get_available_timer()` is actually an `int8`, but in Arduino_LED_Matrix.h is stored as `uint8`.
Therefore the following if (added in #282) cannot work as intended:
https://github.com/arduino/ArduinoCore-renesas/blob/2c8dd5744a161e04b304a6105f85b6e616d8256b/libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h#L175-L178
This PR is to use the correct datatype. Ideally it should have been included in my previous PR.

Use correct datatype for return value of FspTimer::get_available_timer()

---

libraries/Arduino_FreeRTOS/src/Arduino_FreeRTOS.h

Changes "CAN library" to "FreeRTOS library".

Correct name of library in file header

---

svd/R7FA4M1AB.svd

This fixes #276 and also incorrect definitions of Port1, Port2 and Port4.
Please refer to the repo https://github.com/embedded-kiddie/R7FA4M1AB .

Update "Port mn Pin Function Select Register" in SVD file.

---

libraries/Arduino_LED_Matrix/examples/DisplaySingleFrame/DisplaySingleFrame.ino
libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

This method makes it easy to turn off the matrix.

Add a clear() method to the LED matrix library

---

libraries/Wire/Wire.cpp
libraries/Wire/Wire.h

Two pointer arrays declared, which contain pointers to the global SCI/I2C Wire instances: "g_SCIWires" and "g_I2CWires". Since there's a different number of SCI vs pure I2C "I2C" interfaces those buffers are of different size. Due to a typo the constant declaring the size of the pointe rarray for "g_SCIWires" ("TWOWIRE_MAX_SCI_CHANNELS") was used to define the size of "g_I2CWires" and vice versa. This had the result that on Portenta C33, íf you were calling "TwoWire::_begin()" for "Wire3" (which has channel "3") a buffer overflow occurs and random memory is overwritten.

Fix buffer-overflow assigning global Wire instances.

---

cores/arduino/IRQManager.cpp
cores/arduino/IRQManager.h

I'm proposing this as an alternative to #315 that keeps the dangerous code inside the IRQManager class.  This is a fix for #310
@facchinm would something like this work as an alternative?
Here's a test sketch.  I know we already have attachInterrupt for pin interrupts, but I already had this set up for testing.
```
#include "IRQManager.h"
volatile bool interruptFired = false;
GenericIrqCfg_t cfg;
void setup() {
Serial.begin(115200);
while (!Serial)
;
Serial.println("\n\n *** " __FILE__ " ***\n\n");
R_ICU->IRQCR[0] = 0xB0;  // Configure some peripheral for an interrupt
// Create a generic interrupt configuration and attach
cfg.irq = FSP_INVALID_VECTOR;
cfg.ipl = 12;
cfg.event = ELC_EVENT_ICU_IRQ0;  
IRQManager::getInstance().addGenericInterrupt(cfg, Myirq0_callback);
// Enable the …
```

Adding Generic Interrupt function to IRQManager

---

libraries/SE05X/src/lib/platform/arduino/sm_port.cpp
libraries/SSLClient/src/ssl_debug.cpp
libraries/WiFiS3/src/Modem.cpp
libraries/lwIpWrapper/src/CNetIf.cpp

`vsprintf` should be avoided as it could easily overflow the buffer if the formatted string exceeds the max buffer size. `vsnprintf`, on the other hand, checks a buffer size argument. Note that they both null-terminate the string, so calling `memset` beforehand is not necessary.

libraries: Fix possible buffer/stack overflows in multiple libraries.

---

libraries/Wire/Wire.cpp

It has been observed on I2C bus with heavy load of traffic that sometimes after the call of end() from a slave, the I2C bus gets in a weird state in which the master is not more able to start an I2C transaction correctly: this commits fixes this problem.

Fix for I2C bus not always working correctly after a slave device call end()

---

platform.txt

Adding extra flags for compilation (e.g. global defines) is possible via `compiler.xxx.extra_flags` in receipes for other platfomrs (AVR, SAMD).
But this is not possible for this platfomr since this variable is not used in the receipe definition.

Add compiler.xxx.extra_flags to receipes in platform.txt

---

libraries/Ethernet/src/Ethernet.cpp
libraries/Ethernet/src/EthernetC33.h
libraries/Ethernet/src/EthernetClock.cpp
libraries/Ethernet/src/EthernetClock.h
variants/PORTENTA_C33/pins_arduino.h
variants/PORTENTA_C33/variant.cpp

**Description:**
This pull request addresses an issue with inconsistent sleep current consumption on the board. Previously, the board would sometimes draw around 100µA and other times around 2mA. After thorough investigation, it was determined that the issue was due to the lowest power supply state (LPM_POWER_SUPPLY_DEEPCUT3) of the Renesas RA6M5 chip turning off the AGT (Asynchronous General Purpose Timer), which conflicted with the AGT timer used for the Ethernet clock defined in variant.cpp.
**Changes:**
- Removed the AGT timer definition for the Ethernet clock in variant.cpp.
- Wrapped the AGT timer functionality in the EthernetClock class
- Added timer instantiation in the begin method of the Ethernet class.
- Added timer deletion in the disconnect method of the Ethernet class. …

 Fix Inconsistent Sleep Current by relocating the Ethernet Clock AGT Timer 

---

libraries/WiFiS3/src/Modem.cpp
libraries/WiFiS3/src/Modem.h

This makes the compiler more happy

WiFiS3 Modem: change write and write_nowait format argument to const char *

---

cores/arduino/IRQManager.cpp
cores/arduino/IRQManager.h

Based on discussion from #316 I'm proposing this pull to add bounds checking for the last_interrupt_index to all functions in the IRQManager class that add interrupts.

bounds check for last_interrupt_index

---

libraries/RTC/src/RTC.cpp
libraries/RTC/src/RTC.h

This PR adds a new setter that doesn't require to pass an alarm callback. This is useful in Low Power scenarios in which the board resets after being woken up from the RTC. Therefore the callback would never be called anyway.

Add RTC alarm setter without callback

---

cores/arduino/IRQManager.cpp
cores/arduino/IRQManager.h
libraries/I2S/I2S.cpp
libraries/I2S/I2S.h
libraries/I2S/config.c
libraries/I2S/examples/RecordAndStream/RecordAndStream.ino
variants/PORTENTA_C33/pins_arduino.h

Supersedes https://github.com/arduino/ArduinoCore-renesas/pull/256
This PR depends on:

Add I2S support.

---

variants/MINIMA/pins_arduino.h
variants/UNOWIFIR4/pins_arduino.h

Defining digitalPinHasPWM will make that those sketches using it from older boards, like UNO R3 or Nano, can also be used with UNO R4, without extra complications for non advanced users (like me).

define digitalPinHasPWM for UNOWIFIR4 & MINIMA

---

libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

In the 1.2.0 update, the override of ArduinoLEDMatrix::clear() only cleared the frame buffer, but not the canvas buffer (Issue #336).
This resulted in pixels staying on in animations using matrix.beginDraw(), matrix.set(x, y, r, g, b), matrix.endDraw() even after a call to clear().

Clearing canvas buffer in ArduinoLEDMatrix::clear() in addition to frame buffer

---

post_install.sh

The Arduino Boards Manager automatically executes the `post_install.sh` script during installation of the platform on a Linux machine:
https://arduino.github.io/arduino-cli/dev/platform-specification/#post-install-script
This platform's post-install script is intended to create a [**udev** rules file](https://man7.org/linux/man-pages/man7/udev.7.html#RULES_FILES) that gives write permissions for the USB devices of the platform's boards. These permissions are required in order to upload to the boards.
The creation of the udev rules file requires superuser privileges, which are typically not available in the context of the post-install script's execution by the Arduino development software. The script contains code to [check whether the necessary privileges are …

Display useful message when Linux post-install script has insufficient permissions

---

libraries/WiFiS3/src/WiFi.cpp

Fixes https://github.com/arduino/ArduinoCore-renesas/issues/337

WiFiS3: implement setTimeout functionality

---

libraries/AnalogWave/examples/DACEqualTemperedScale/DACEqualTemperedScale.ino

The stated formula for converting midi-notes to frequency is wrong – the base and exponent of the second factor should be interchanged

Fix in formula for creating frequency from MIDI note

---

post_install.sh

The Arduino Boards Manager automatically executes the `post_install.sh` script during installation of the platform on a non-Windows machine:
https://arduino.github.io/arduino-cli/dev/platform-specification/#post-install-script
The platform's post-install script is Linux-specific, but no provisions were made in the script code for the fact that it is also executed on macOS machines. Previously, this was fairly innocuous because, although misleading, the message printed to the output during the platform installation was short and cryptic and thus easy for the average macOS user to ignore:
```text
Configuring platform.
Please run as root
```
Since it is important for Linux users to manually run the script and the previous message did not effectively communicate that, the script was recently …

Configure post-install script to only operate when platform installed on Linux machine

---

extras/e2studioProjects/Santiago/configuration.xml
extras/e2studioProjects/Santiago/ra_cfg.txt
extras/e2studioProjects/portenta_h33_lib/configuration.xml
extras/e2studioProjects/portenta_h33_lib/ra_cfg.txt
libraries/RTC/examples/RTC_Reset/RTC_Reset.ino
libraries/RTC/examples/Test_RTC/Test_RTC.ino
libraries/RTC/src/RTC.cpp
libraries/RTC/src/RTC.h
variants/MINIMA/includes/ra_cfg/fsp_cfg/r_rtc_cfg.h
variants/PORTENTA_C33/includes/ra_cfg/fsp_cfg/r_rtc_cfg.h
variants/UNOWIFIR4/includes/ra/arm/CMSIS_5/CMSIS/Core/Include/cmsis_version.h
variants/UNOWIFIR4/includes/ra/arm/CMSIS_5/CMSIS/Core/Include/core_armv81mml.h
variants/UNOWIFIR4/includes/ra/arm/CMSIS_5/CMSIS/Core/Include/core_armv8mml.h
variants/UNOWIFIR4/includes/ra/arm/CMSIS_5/CMSIS/Core/Include/core_cm33.h
variants/UNOWIFIR4/includes/ra/arm/CMSIS_5/CMSIS/Core/Include/core_cm35p.h
variants/UNOWIFIR4/includes/ra/arm/CMSIS_5/CMSIS/Core/Include/core_cm55.h
variants/UNOWIFIR4/includes/ra_cfg/fsp_cfg/r_rtc_cfg.h

This PR aims to fix the issue described here https://github.com/arduino/ArduinoCore-renesas/issues/181. 
The issue can be described as follow: When the board is reset, or powered off with VRTC powered, the RTC time value is reset.

Fix RTC resetting after reboot

---

libraries/WiFiS3/src/Modem.cpp

When network goes down (WiFi is up but no internet connection) AT message parsing gets corrupted due to late reply from WiFi chip. This PR fixes the issue discarding unaligned responses from WiFi chip .

WiFiS3: Skip unaligned responses from WiFi chip

---

cores/arduino/FspTimer.cpp

In some cases (essentially with low frequencies) the calculation of pulse value was wrong due to an erroneous calculation order

Core Renesas / PWM / fixing wrong pulse setting 

---

libraries/SoftwareSerial/src/SoftwareSerial.cpp

After transferring the last stop bit the TX GPIO needs to stay high until the trigger timer cycle is complete, otherwise the stop bit time will be short and the receiver may fail to decode it.
I tested baudrates 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600 and 115200, and all of them can be decoded successfully by the scope. All baudrates up to 19200 have a stop bit time exactly the same as the bit time. For example 9600:
For baudrates higher than 19200, the stop bit time looks like it's slightly longer than nominal bit time, but this is just because it starts to get less than the time required to loop around and send the next byte. The worst case for 115200 is around 8us:
Fixes https://github.com/arduino/uno-r4-library-compatibility/issues/12

Fix stop bit time.

---

libraries/BlockDevices/CodeFlashBlockDevice.cpp
libraries/BlockDevices/MBRBlockDevice.cpp
libraries/BlockDevices/QSPIFlashBlockDevice.cpp
libraries/FATFilesystem/FATFileSystem.cpp
libraries/Storage/storage_common.cpp
libraries/Storage/storage_common.h

Renamed storage debug function to avoid clash with user code

Core renesas / Storage library, Fix for #366 (Name conflict in library Storage) 

---

libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphicsAsynchronous/TextWithArduinoGraphicsAsynchronous.ino
libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
libraries/Arduino_LED_Matrix/src/TextAnimation.h

I implemented support for generating animation (sequence) from text input. This can be later used for scrolling text asynchronously instead of doing it using `endText` which blocks execution untill text scroll is done on display.
The new proposed API contains TEXT_ANIMATION_DEFINE macro (in new file TextAnimation.h) which (staticaly) declare buffer for specified number of frames. The API for sequences requires static number of frames, but this new API can dynamicaly adjust length of sequence depending on text length up to limit specified in second TEXT_ANIMATION_DEFINE parameter. For example:
TEXT_ANIMATION_DEFINE(anim, 100)
declare buffers for up to 100 frames which is 20 characters using font 5x7 or 25 characters using font 4x6.
Then you can render text in exactly the same way as …

Add support for scrolling text asynchronously

---

libraries/WiFiS3/examples/WiFiPing/WiFiPing.ino
libraries/WiFiS3/examples/WiFiPing/arduino_secrets.h
libraries/WiFiS3/src/WiFi.cpp
libraries/WiFiS3/src/WiFi.h
libraries/WiFiS3/src/WiFiTypes.h

Add WiFi.ping()

---

libraries/WiFiS3/src/Modem.cpp
libraries/WiFiS3/src/WiFi.cpp
libraries/WiFiS3/src/WiFi.h

This functionality depends on https://github.com/arduino/uno-r4-wifi-usb-bridge/pull/54

WifiS3 added method to get uint32 version

---

libraries/WiFiS3/src/Modem.cpp
libraries/WiFiS3/src/Modem.h

Improving the AT parsing function

WiFiS3 At improvements

---

cores/arduino/main.cpp
libraries/Arduino_FreeRTOS/src/portable/FSP/port.c

If anyone can find a better name for `eventually_start_scheduler_and_sketch_task` I'd be very happy :slightly_smiling_face:

Arduino_FreeRTOS: automatically start loop

---

libraries/ESPhost/examples/ESP32_TEST/ESP32_TEST.ino

The AP configuration variable wasn't initialized, so the fields contained random data. Then, they were filled using memcpy() with the size of the data to copy, leaving the remainder of the fields containing random data. For example, the pwd variable containing the entered password was copied without null termination into the pwd field, and the rest of the pwd field contained random data. This caused connection failures depending on the content of the random data.

Initialize local variable for AP config

---

libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphics/TextWithArduinoGraphics.ino
libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphicsAsynchronous/TextWithArduinoGraphicsAsynchronous.ino

TextWithArduinoGraphics: add note about ArduinoGraphics dependency

---

cores/arduino/Serial.cpp
cores/arduino/Serial.h

Fix for Serial flush() returning before transmission has completed

---

libraries/WiFiS3/src/Modem.cpp
libraries/WiFiS3/src/Modem.h

During coldboot first attempt of `_SOFTRESETWIFI` always fails. This patch is to mitigate the issue. Investigation fwside will follow.

UNO R4 WiFi Fix firmware init from cold boot

---

libraries/WiFiS3/src/WiFi.h
libraries/WiFiS3/src/WiFiTypes.h
libraries/lwIpWrapper/src/CNetIf.cpp
libraries/lwIpWrapper/src/CNetIf.h

Fixes: #294 
I've added only WL*_LENGTH definitions because even though they are mostly unused they are handy to declare arrays as explained in the issue.

WiFiS3 and WiFIC3 Add wl definitions

---

libraries/SSLClient/src/SSLClient.cpp
libraries/SSLClient/src/ssl_client.cpp
libraries/SSLClient/src/ssl_client.h
libraries/SSLClient/src/ssl_debug.cpp
libraries/SSLClient/src/ssl_debug.h

Also suppress some othe minor warnings

C33 SSL client fix stop() and connect( .. ) with psk

---

libraries/BlockDevices/QSPIFlashBlockDevice.cpp
libraries/BlockDevices/QSPIFlashBlockDevice.h
libraries/BlockDevices/SDCardBlockDevice.cpp
libraries/BlockDevices/SDCardBlockDevice.h
libraries/Storage/storage_common.h

TestCodeFlash :+1: 
TestQSPI :+1: 
QSPIFormat :+1: 
QSPIReadPartitions :+1: 
FatFSOnQSPIFlash  :+1: 
LittleFSOn QSPIFlash :+1: 
TestSDCard :-1:  (also in released cores)

BlockDevices: minor fixes to cleanup compile warnings

---

boards.txt
cores/arduino/main.cpp
libraries/Arduino_FreeRTOS/src/Arduino_FreeRTOS.h
libraries/Arduino_FreeRTOS/src/portable/FSP/port.c

The default behaviour is do nothing: scheduler has to be started manually by the user.
Use `AUTOSTART_FREERTOS` if you declare tasks in your `setup()` and use them in `loop()`.
Use `EARLY_AUTOSTART_FREERTOS` if you need the scheduler to be already running in `setup()`.
Libraries that need to use threads/semaphores during `setup()` for example, to implement the usual
```
myObj.begin(); <- this starts a thread
while (!myObj) {  <- this becomes true when the thread is unlocked
delay();
}
```
will need to declare `EARLY_START_FREERTOS_HOOK` in one of their cpp files
Also fixes https://github.com/arduino/ArduinoCore-renesas/pull/414#issuecomment-2601163077
/cc @hexnet1234 @gpb01 @Wetmelon

FreeRTOS restore original behaviour and allow override startup hooks

---

.github/workflows/compile-examples.yml
libraries/KVStore/examples/StartCounter/StartCounter.ino
libraries/KVStore/library.properties
libraries/KVStore/src/KVStore.h
libraries/KVStore/src/MbedCRC.h
libraries/KVStore/src/TDBStore.cpp
libraries/KVStore/src/TDBStore.h
libraries/Storage/examples/QSPIFormat/QSPIFormat.ino

Importing KVStore from mbedos to be used with portenta c33

[C33] Kvstore

---

libraries/RTC/examples/Test_RTC/Test_RTC.ino

using 22 on UNO R4 WIFI is braking Serial communication

Test_RTC example: change on interrupt PIN to D7

---

libraries/WiFiS3/src/WiFi.cpp

WiFiS3: remove retries to get localIP

---

libraries/WiFiS3/src/WiFi.cpp
libraries/WiFiS3/src/WiFi.h

During the `WiFi.scanNetworks()` the access points found are stored on a `vector `container. 
The allocation of memory for the `vector` doesn't grow linearly with the increasing of data stored, but logarithmically (view [this ](https://cplusplus.com/reference/vector/vector/) ) and this can hang up the Arduino UNO R4 board for memory saturation when performing a scan inside an enviroment with many APs.
This PR limits the number of element stored inside the vector for returning only the APs with the highest RSSI.

Add limit for returning the first 10 access points with high rssi

---

libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h

The following sketch will display the first frame only for a few ms using core 1.4.1. Removing the delay(1200) from the sketch the first frame duration is correct. Initializing _lastInterval will make it work also with the delay.
```
#include "Arduino_LED_Matrix.h"
ArduinoLEDMatrix matrix;
const uint32_t snake[][4] = {
{ 0xffffffff, 0xffffffff, 0xffffffff, 1300 },
{ 0x7fffffff, 0xffffffff, 0xfffff7ff, 66 },
{ 0x3fe7ffff, 0xffffffff, 0xff7ff3fe, 66 },
{ 0x1fc3fe7f, 0xfffffff7, 0xff3fe1fc, 66 },
{ 0xf81fc3f, 0xe7ff7ff3, 0xfe1fc0f8, 66 },
{ 0x500f81f, 0xc3fe3fe1, 0xfc0f8070, 66 },
{ 0x500f, 0x81fc1fc0, 0xf8070020, 66 },
{ 0x5, 0xf80f80, 0x70020000, 66 },
{ 0x5, 0xa80880, 0x50020000, 600 },
{ 0xd812, 0x41040880, 0x50020000, 200 },
{ 0x5, 0xa80880, 0x50020000, 600 },
{ 0xd812, 0x41040880, …
```

Matrix: initialize _lastInterval when starting a sequence

---

libraries/lwIpWrapper/src/CNetIf.cpp

List of changes:
- check manually the ptr validity instead of using the `LWIP_ASSERT` macro
- use pseudo random generator for icmp packet sequence number instead of the _true random number generator_
These changes will reduce the memory and storage consumption of 20KB

Reduce storage consumption of ping command for C33
